services:
  block-watcher:
    image: ghcr.io/femavibes/bsky-block-countermod:latest
    container_name: bsky-block-countermod
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
    environment:
      - NODE_ENV=production